AWSTemplateFormatVersion: 2010-09-09

Description: Creates an ECS Cluster

Parameters:
  ClusterName:
    Type: String
    Default: FargateEcsCluster

  VpcId:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
      Tags:
        - Key: Owner
          Value: !Ref Owner

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Sg${ClusterName}
      GroupDescription: !Sub Sg${ClusterName}
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
